const FieldName = {
    'alignmentFiles': 'alignmentFile',
    'bimFiles': 'bimFile',
    'config.length': 'length',
    'config.measureStation': 'measureStation',
    'config.sequentStation': 'continuousStation',
    'config.station': 'brokenChainStation',
    'config.sumLong': 'sumLong',
    'config.sumShort': 'sumShort',
    'config.type': 'type',
    'leftPart.alignmentCnName': 'leftAlignmentCnName',
    'leftPart.alignmentID': 'leftAlignmentID',
    'leftPart.endStation': 'leftEndStation',
    'leftPart.endStationChain': 'leftEndStationChain',
    'leftPart.startStation': 'leftStartStation',
    'leftPart.startStationChain': 'leftStartStationChain',
    'leftPart.stationMark': 'leftStationMark',
    'rightPart.alignmentCnName': 'rightAlignmentCnName',
    'rightPart.alignmentID': 'rightAlignmentID',
    'rightPart.endStation': 'rightEndStation',
    'rightPart.endStationChain': 'rightEndStationChain',
    'rightPart.startStation': 'rightStartStation',
    'rightPart.startStationChain': 'rightStartStationChain',
    'rightPart.stationMark': 'rightStationMark',
    'Section.alignmentCnName': 'alignmentCnName',
    'Section.alignmentID': 'alignmentID',
    'Section.endStation': 'alignmentEndStation',
    'Section.endStationChain': 'alignmentEndStationChain',
    'Section.startStation': 'alignmentStartStation',
    'Section.startStationChain': 'alignmentStartStationChain',
    'Section.stationMark': 'alignmentStationMark',
    'sectionID': 'section',
    'serviceareaCnName': 'serviceAreaCnName',
    'serviceareaEnName': 'serviceAreaEnName',
    'stopCnName': 'parkingAreaCnName',
    'stopEnName': 'parkingAreaEnName',
};

export default FieldName;
